name: Build and Push IndexTTS 2 Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version tag'
        required: true
        default: 'latest'
      push_to_registry:
        description: 'Push to GitHub Container Registry'
        type: boolean
        default: true

env:
  IMAGE_NAME: index-tts-2
  REGISTRY_NAMESPACE: andrewkapok

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Clean up disk space before build
      run: |
        echo "清理磁盘空间..."
        df -h
        
        # 清理系统缓存
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        # 清理 Docker 缓存和镜像
        docker system prune -a -f || true
        
        # 清理 GitHub Actions 缓存
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /opt/microsoft
        sudo rm -rf /opt/hostedtoolcache
        
        # 清理日志文件
        sudo find /var/log -type f -name "*.log" -exec truncate -s 0 {} \; 2>/dev/null || true
        
        echo "清理后磁盘空间:"
        df -h

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx with disk limits
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          # 限制磁盘使用
          disk.space=8G

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'workflow_dispatch' && inputs.push_to_registry || github.event_name != 'workflow_dispatch'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image with resource limits
      run: |
        echo "Building Docker image with resource limits..."
        DOCKER_BUILDKIT=1 docker buildx build \
          --platform linux/amd64 \
          --tag ghcr.io/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }} \
          --tag ghcr.io/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest \
          --push \
          --memory=4G \
          --shm-size=512M \
          --ulimit nofile=1024:1024 \
          .
      env:
        BUILDKIT_PROGRESS: plain

    - name: Clean up after build
      run: |
        echo "构建后清理..."
        docker system prune -f
        df -h

    - name: Push to GitHub Packages
      if: github.event_name == 'workflow_dispatch' && inputs.push_to_registry || github.event_name != 'workflow_dispatch'
      run: |
        echo "Image successfully pushed to GitHub Container Registry"
        echo "Image: ghcr.io/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}"